### ISSUE TITLE
Errors Canton Vaud

### ISSUE THREAD

**Issue by nrohrbach** [SFOE/SuitabilityGeothermalDrillingSwitzerland#2]
Queries in the canton of Vaud currently lead to an error. The reason lies in an update of ArcGIS Enterprise. We will fix the error as soon as possible.

**Comment by geocode-ch** [comment]
fixed in latest release [v1.0.16](https://github.com/SFOE/SuitabilityGeothermalDrillingSwitzerland/releases/tag/v1.0.16)
