### ISSUE TITLE
Changes in WMS SZ

### ISSUE THREAD

**Issue by nrohrbach** [SFOE/SuitabilityGeothermalDrillingSwitzerland#3]
Sie beziehen unseren WMS-Layer «ch.sz.a034c.waermenutzung.erdwaerme». 
Ich möchte Sie darüber informieren, dass das Attribut "zulaessigkeit_cd" am 5. Dezember 2023 aus dem Layer "ch.sz.a034c.waermenutzung.erdwaerme" entfernt wird. 
Das Attribut ist ab sofort im Layer "ch.sz.a034c.waermenutzung.erdwaerme.technisch" verfügbar.

**Comment by geocode-ch** [comment]
fixed in the [latest release](https://github.com/SFOE/SuitabilityGeothermalDrillingSwitzerland/releases/tag/v1.0.17)

**Comment by geocode-ch** [comment]
please update the cantons.json
