### ISSUE TITLE
WMS Kanton Bern unavailable

### ISSUE THREAD

**Issue by nrohrbach** [SFOE/SuitabilityGeothermalDrillingSwitzerland#4]
Sehr geehrte Damen und Herren

Für die Webseite [www.kann-ich-bohren.ch](http://www.kann-ich-bohren.ch/)  des BFE haben wir bis letzte Woche erfolgreich Ihren kantonalen WMS zu «Zulässigkeit Erdwärmesonden» abfragen können. Leider ist der uns bekannte WMS von Ihnen nicht mehr erreichbar:
https://www.geoservice.apps.be.ch/geoservice2/services/a42geo/a42geo_versorgungwms_d_fk/MapServer/WmsServer mit dem Layer GEODB.ERDSOND_ERDSOND_KMGDM1

Können Sie uns bitte mitteilen ob, wo und wie Ihr WMS zu «Zulässigkeit Erdwärmesonden» verfügbar ist? Der von Ihnen dokumentierte Layer ist nicht öffentlich zugänglich:
https://www.geo2.apps.be.ch/?type=layer&code=ERDSOND&mode=c

Vielen Dank im Voraus für Ihre Rückmeldung.

Beste Grüsse,

**Comment by geocode-ch** [comment]
MapServer and layer from the canton of Bern is available again

**Comment by OliverFrey** [comment]
Same problem again

**Comment by OliverFrey** [comment]
New WMS Server Url implemented
